### PR TITLE
Separate command.

### PR DESCRIPTION
**Pull request by MikkelDK**
Updated with technical pause separate.

**Bug with command > after updated, eBot is offline**

### CODE REVIEW

**Comment by heew** [comment]
The else statement starting on line 1308 has no closing braces.

**Comment by MikkelDK** [comment]
> The else statement starting on line 1308 has no closing braces.

Seems it's this error:
`            } else {`

**Comment by MikkelDK** [comment]
Let's wait with the look of the commands trigger. @heew 
Let's focus and see, about we can do something.. so we can get eBot to work, so it's possible "create new match".

I have contacted an author, who has the function with: 

> pause_duration
> nr_tac_pauses
> ct_tac_pauses
> t_tac_pauses

**Comment by MikkelDK** [comment]
Found out the extra fields of "tac function" don't support HTTPS! ;/ 

I will close this.

**Pull request closed without merging**
